[package]
name = "notion-formatter"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
thiserror = "1.0.61"
regex = "1.10.4"
lazy_static = "1.4.0"
image = { version = "0.25.1", features = ["png", "jpeg"] }
urlencoding = "2.1.3"
