# .github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary-name: notion-formatter
          - os: macos-latest
            target: x86_64-apple-darwin
            binary-name: notion-formatter
          - os: macos-latest
            target: aarch64-apple-darwin
            binary-name: notion-formatter
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary-name: notion-formatter.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create package directory
        run: mkdir -p bin/${{ matrix.target }}

      - name: Move binary to package directory
        run: mv target/${{ matrix.target }}/release/${{ matrix.target.os == 'windows-latest' && matrix.binary-name || matrix.binary-name }} bin/${{ matrix.target }}/

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/${{ matrix.target }}/${{ matrix.binary-name }}
          asset_name: notion-formatter-${{ matrix.target }}
          tag: ${{ github.ref }}
          overwrite: true
